<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="71474" started-at="2017-10-09T02:41:37Z" finished-at="2017-10-09T02:42:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="71474" started-at="2017-10-09T02:41:37Z" finished-at="2017-10-09T02:42:48Z">
      <class name="com.four.testcase.TestCase">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.four.testcase.TestCase@59fa1d9b]" name="beforeClass" is-config="true" duration-ms="12812" started-at="2017-10-09T10:41:37Z" finished-at="2017-10-09T10:41:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="huoZhuAppExceution()[pri:0, instance:com.four.testcase.TestCase@59fa1d9b]" name="huoZhuAppExceution" duration-ms="45988" started-at="2017-10-09T10:41:50Z" finished-at="2017-10-09T10:42:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- huoZhuAppExceution -->
        <test-method status="PASS" signature="xaioErExceution()[pri:0, instance:com.four.testcase.TestCase@59fa1d9b]" name="xaioErExceution" duration-ms="10057" started-at="2017-10-09T10:42:36Z" finished-at="2017-10-09T10:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- xaioErExceution -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.four.testcase.TestCase@59fa1d9b]" name="afterClass" is-config="true" duration-ms="2602" started-at="2017-10-09T10:42:46Z" finished-at="2017-10-09T10:42:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.four.testcase.TestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
